services:
  backend:
    build:
      context: .
      target: backend-builder
    ports:
      - "3000:3000"
    environment:
      - HOST=${HOST}
    volumes:
      - ${VIDEOS_PATH}:/videos
      - ${RESULTS_PATH}:/results

  frontend:
    build:
      context: .
      target: frontend-builder
    environment:
      - NEXT_PUBLIC_HOST=${HOST}
    ports:
      - "3001:3001"