name: Publish images
# Trigger section
on:
  push: # on push to repository
    if: github.repository == 'Jameson789/centroid-finder'
    branches: [ deploy ] # only if push is to deploy
    paths: # only if changes are within this path
      - '.'
  workflow_dispatch: # allows manual triggers from github UI

jobs:
  build:
    runs-on: ubuntu-latest # clean linux VM provided by github
    permissions:
      contents: read
      packages: write
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up docker buildx builder
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr.io 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # username of whoever triggered workflow
          password: ${{ secrets.GITHUB_TOKEN }} #built in gh token that authenticates the workflow
      - name: format repository owner string
        uses: actions/github-script@v4
        id: repo_lower
        with:
          result-encoding: string
          script: return `ghcr.io/${github.repository_owner.toLowerCase()}`
      - name: generates metadata for backend docker image
        uses: docker/metadata-action@v5
        id: meta-backend
        with:
          images: ghcr.io/${{ github.repository_owner }}/centroid-finder-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: generates metadata for frontend docker image
        uses: docker/metadata-action@v5
        id: meta-frontend
        with:
          images: ghcr.io/${{ github.repository_owner }}/centroid-finder-frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: backend-builder
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ steps.repo_lower.outputs.result }}/centroid-finder-backend:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ steps.repo_lower.outputs.result }}/centroid-finder-backend:buildcache,mode=max
      - name: build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: frontend-builder
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ steps.repo_lower.outputs.result }}/centroid-finder-frontend:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ steps.repo_lower.outputs.result }}/centroid-finder-frontend:buildcache,mode=max
