name: Publish images
# Trigger section
on:
  push: # on push to repository
    if: github.repository == 'Jameson789/centroid-finder'
    branches: [ deploy ] # only if push is to deploy
    paths: # only if changes are within this path
      - '.'
  workflow_dispatch: # allows manual triggers from github UI

jobs:
  build:
    runs-on: ubuntu-latest # clean linux VM provided by github
    permissions:
      contents: read
      packages: write
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up docker buildx builder
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr.io 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # username of whoever triggered workflow
          password: ${{ secrets.GITHUB_TOKEN }} #built in gh token that authenticates the workflow
      - name: generates metadata for backend docker image
        uses: docker/metadata-action@v5
        id: meta-backend
        with:
          images: ghcr.io/${{ github.repository_owner }}/centroid-finder-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: generates metadata for frontend docker image
        uses: docker/metadata-action@v5
        id: meta-frontend
        with:
          images: ghcr.io/${{ github.repository_owner }}/centroid-finder-frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Create docker-compose.override.yml
        run: |
          BACKEND_TAG=$(echo "${{ steps.meta-backend.outputs.tags }}" | head -n 1)
          FRONTEND_TAG=$(echo "${{ steps.meta-frontend.outputs.tags }}" | head -n 1)
          echo "using: $BACKEND_TAG"
          echo "using: $FRONTEND_TAG"

          cat <<EOF > docker-compose.override.yml
          services:
            backend:
              image: $BACKEND_TAG
              volumes: null
            frontend:
              image: $FRONTEND_TAG
              volumes: null
          EOF

      - name: Build images
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml build

      - name: Push images
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml push
